namespace Manuela;

public enum ManuelaProperty
{
    Background,
    Margin,
    Padding,
    BorderColor,
    BorderThickness,
    BorderRadius,
    Shadow,
    TextSize,
    LineHeight,
    FontAttributes,
    VerticalTextAlign,
    HorizontalTextAlign,
    TextColor,
    TextDecoration,
    VerticalOptions,
    HorizontalOptions,
    Opacity,
    Width,
    Height,
    XAnchor,
    YAnchor,
    TranslateX,
    TranslateY,
    Rotation,
    RotationX,
    RotationY,
    Scale,
    ScaleX,
    ScaleY,
}
