using Microsoft.CodeAnalysis;

namespace Manuela.Generation;

public class XamlStateTemplate
{
    public static void Generate(SourceProductionContext context, TemplateParams templateParams)
    {
        context.AddSource(
            $"{templateParams.TypeName}.g.cs",
            @$"// <auto-generated />
using System.ComponentModel;
using Manuela.Styling.ConditionalStyles;

namespace {templateParams.Namespace};

public partial class {templateParams.TypeName}
{{
    protected override void OnInitialized(VisualElement visualElement)
    {{
        Condition = new Manuela.Expressions.XamlCondition(IsActive);
        var triggers = new Dictionary<INotifyPropertyChanged, Manuela.Expressions.Trigger>();
        var evaluation = GetNotifiers(visualElement, triggers);
        Condition.Triggers = [.. triggers.Values];
    }}

    private bool GetNotifiers(
        VisualElement {templateParams.VisualElementParamName},
        Dictionary<INotifyPropertyChanged, Manuela.Expressions.Trigger> triggers)
    {templateParams.NotifiersSyntax}
}}
");
    }
}
