namespace Manuela.Styling;

// there is no specific order in this enum.. this is just the order they were added to the enum.

public enum ManuelaProperty
{
    Background,
    Margin,
    Padding,
    BorderColor,
    BorderThickness,
    BorderRadius,
    Shadow,
    TextSize,
    LineHeight,
    FontAttributes,
    VerticalTextAlign,
    HorizontalTextAlign,
    TextColor,
    TextDecoration,
    VerticalOptions,
    HorizontalOptions,
    Opacity,
    Width,
    Height,
    XAnchor,
    YAnchor,
    TranslateX,
    TranslateY,
    Rotation,
    RotationX,
    RotationY,
    Scale,
    ScaleX,
    ScaleY,
    MaxWidth,
    MaxHeight,
    MinWidth,
    MinHeight,
    Visible,
    Style,
    AbsoluteLayoutBounds,
    AbsoluteLayoutFlags,
    ImageSource
}
